import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import Head from 'next/head';
import Script from 'next/script';


export const metadata = {
  title: 'সহজ শেখা',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script
        id="email-js-cdn"
        type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"
      />
      <Script id='email-js-fn' type="text/javascript">
        {`
            (function(){
               emailjs.init("olyq2I1iF1OuD1Sel");
            })();
          `}
      </Script>
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
